# Financial Report Standardization & Cleaning Pipeline

This notebook automates the loading, cleaning, and standardization of quarterly financial report data for Israeli companies, from Q1 2020 through full-year 2021. It reads raw JSON reports from Google Drive, unifies similar company names using fuzzy matching and manual rules, and maps them to official tickers using an Excel reference. The data is deduplicated by selecting the most complete entry per company and saved back to Drive for further analysis. While the paths reference a specific Q1 2021 example, the same pipeline is applied across all time periods consistently.

### Imports:

In [38]:
!pip install rapidfuzz

Requirement already satisfied: rapidfuzz in /usr/local/lib/python3.11/dist-packages (3.13.0)

In [39]:
import pandas as pd
import numpy as np
import json

from rapidfuzz import process, fuzz
from collections import defaultdict


import re

import ast

### Mounting to drive:

In [40]:
# connect to drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

### Reading & presenting example file:

In [41]:
# read json file from path /content/drive/Shareddrives/capstone project-stock market robo-advisor/Reports Parameters/financial_reports_q1_2021.json with utf-8
with open('/content/drive/Shareddrives/capstone project-stock market robo-advisor/Reports Parameters/financial_reports_q1_2021.json', 'r', encoding='utf-8') as f:
    financial_reports_q1_2021 = json.load(f)

In [42]:
financial_reports_q1_2021

[{'Company Name': 'Tel Aviv Stock Exchange',
  'Report Date': 'March 31, 2021',
  'Revenue': 'N/A',
  'Net Income': 'N/A',
  'Earnings Per Share (EPS)': 'N/A',
  'Gross Profit': 'N/A',
  'Operating Income (EBIT)': 'N/A',
  'Operating Cash Flow': 'N/A',
  'Investing Cash Flow': 'N/A',
  'Financing Cash Flow': 'N/A',
  'Total Assets': '890,388,000',
  'Total Liabilities': '265,772,000',
  'Short-Term Debt': 'N/A',
  'Long-Term Debt': 'N/A',
  'Shareholders’ Equity': '624,616,000',
  'Dividends Paid': '18,450,000',
  'Number of Outstanding Shares': 'N/A',
  'Guidance/Forecast': 'N/A',
  'Key Performance Indicators (KPIs)': 'N/A'},
 {'Company Name': 'S.N. Shnepp & Sons Ltd.',
  'Report Date': 'March 31, 2021',
  'Revenue': '415,370,000',
  'Net Income': '29,917,000',
  'Earnings Per Share (EPS)': '1.78',
  'Gross Profit': '108,080,000',
  'Operating Income (EBIT)': '41,995,000',
  'Operating Cash Flow': 'N/A',
  'Investing Cash Flow': 'N/A',
  'Financing Cash Flow': 'N/A',
  'Total Assets': '513,816,000',
  'Total Liabilities': '200,165,000',
  'Short-Term Debt': 'N/A',
  'Long-Term Debt': 'N/A',
  'Shareholders’ Equity': '307,939,000',
  'Dividends Paid': '10,000,000',
  'Number of Outstanding Shares': 'N/A',
  'Guidance/Forecast': 'N/A',
  'Key Performance Indicators (KPIs)': 'N/A'},
 {'Company Name': 'Golan Plastic Products Ltd',
  'Report Date': 'March 31, 2021',
  'Revenue': '83,310,000',
  'Net Income': '28,681,000',
  'Earnings Per Share (EPS)': '0.86',
  'Gross Profit': '24,972,000',
  'Operating Income (EBIT)': '11,974,000',
  'Operating Cash Flow': '47,095,000',
  'Investing Cash Flow': '-30,151,000',
  'Financing Cash Flow': '-10,281,000',
  'Total Assets': '446,179,000',
  'Total Liabilities': '231,531,000',
  'Short-Term Debt': '33,800,000',
  'Long-Term Debt': '28,966,000',
  'Shareholders’ Equity': '224,978,000',
  'Dividends Paid': 'N/A',
  'Number of Outstanding Shares': 'N/A',
  'Guidance/Forecast': 'N/A',
  'Key Performance Indicators (KPIs)': 'N/A'},
 {'Company Name': 'Orian S.M. Ltd.',
  'Report Date': 'March 31, 2021',
  'Revenue': '64,940,000',
  'Net Income': '4,135,000',
  'Earnings Per Share (EPS)': '0.21',
  'Gross Profit': '5,510,000',
  'Operating Income (EBIT)': '2,432,000',
  'Operating Cash Flow': '15,264,000',
  'Investing Cash Flow': '-32,820,000',
  'Financing Cash Flow': '30,678,000',
  'Total Assets': '301,975,000',
  'Total Liabilities': '225,363,000',
  'Short-Term Debt': '8,103,000',
  'Long-Term Debt': '33,409,000',
  'Shareholders’ Equity': '76,612,000',
  'Dividends Paid': 'N/A',
  'Number of Outstanding Shares': '13,556,686',
  'Guidance/Forecast': 'N/A',
  'Key Performance Indicators (KPIs)': 'N/A'},
 [{'Company Name': 'Bikurei Sadeh (Holdings)',
   'Report Date': 'March 31, 2021',
   'Revenue': '1,175,232,000',
   'Net Income': '99,133,000',
   'Earnings Per Share (EPS)': '0.84',
   'Gross Profit': '288,159,000',
   'Operating Income (EBIT)': '109,095,000',
   'Operating Cash Flow': '52,850,000',
   'Investing Cash Flow': '-20,003,000',
   'Financing Cash Flow': '-39,082,000',
   'Total Assets': '832,648,000',
   'Total Liabilities': '261,531,000',
   'Short-Term Debt': '163,594,000',
   'Long-Term Debt': '261,531,000',
   'Shareholders’ Equity': '85,381,000',
   'Dividends Paid': 'N/A',
   'Number of Outstanding Shares': 'N/A',
   'Guidance/Forecast': 'N/A',
   'Key Performance Indicators (KPIs)': 'N/A'}],
 [{'Company Name': 'Bicuri Sadeh',
   'Report Date': 'May 23, 2021',
   'Revenue': 'N/A',
   'Net Income': 'N/A',
   'Earnings Per Share (EPS)': 'N/A',
   'Gross Profit': 'N/A',
   'Operating Income (EBIT)': 'N/A',
   'Operating Cash Flow': 'N/A',
   'Investing Cash Flow': 'N/A',
   'Financing Cash Flow': 'N/A',
   'Total Assets': 'N/A',
   'Total Liabilities': 'N/A',
   'Short-Term Debt': 'N/A',
   'Long-Term Debt': 'N/A',
   'Shareholders’ Equity': 'N/A',
   'Dividends Paid': 'N/A',
   'Number of Outstanding Shares': 'N/A',
   'Guidance/Forecast': 'N/A',
   'Key Performance Indicators (KPIs)': 'N/A'},
  {'Company Name': 'Bicuri Sadeh',
   'Report Date': 'February 2021',
   'Revenue': '1277541000',
   'Net Income': '40829000',
   'Earnings Per Share (EPS)': 'N/A',
   'Gross Profit': '275580000',
   'Operating Income (EBIT)': '53624000',
   'Operating Cash Flow': 'N/A',
   'Investing Cash Flow': 'N/A',
   'Financing Cash Flow': 'N/A',
   'Total Assets': '508663000',
   'Total Liabilities': '213154000',
   'Short-Term Debt': '68726000',
   'Long-Term Debt': '2352000',
   'Shareholders’ Equity': '293157000',
   'Dividends Paid': 'N/A',
   'Number of Outstanding Shares': 'N/A',
   'Guidance/Forecast': 'N/A',
   'Key Performance Indicators (KPIs)': 'EBITDA:75061000'}],
 {'Company Name': 'BiomX Inc.',
  'Report Date': 'March 31, 2021',
  'Revenue': 'N/A',
  'Net Income': '-8,402,000',
  'Earnings Per Share (EPS)': '-0.35',
  'Gross Profit': 'N/A',
  'Operating Income (EBIT)': '-8,670,000',
  'Operating Cash Flow': '-6,400,000',
  'Investing Cash Flow': 'N/A',
  'Financing Cash Flow': 'N/A',
  'Total Assets': '67,062,000',
  'Total Liabilities': '13,108,000',
  'Short-Term Debt': 'N/A',
  'Long-Term Debt': 'N/A',
  'Shareholders’ Equity': '53,954,000',
  'Dividends Paid': 'N/A',
  'Number of Outstanding Shares': '23,944,573',
  'Guidance/Forecast': "Existing cash, cash equivalents and short-term deposits are expected to be sufficient to fund the Company's current operating plan and capital expenditure requirements until at least mid-2022.",
  'Key Performance Indicators (KPIs)': 'Cash balance and short-term deposits: 53,600,000'},
 {'Company Name': 'Orbit Technologies',
  'Report Date': '31/03/2021',
  'Revenue': '12,058,000',
  'Net Income': '857,000',
  'Earnings Per Share (EPS)': '0.046',
  'Gross Profit': '3,908,000',
  'Operating Income (EBIT)': '775,000',
  'Operating Cash Flow': '11,234,000',
  'Investing Cash Flow': '-390,000',
  'Financing Cash Flow': '-3,766,000',
  'Total Assets': '61,331,000',
  'Total Liabilities': '25,631,000',
  'Short-Term Debt': 'N/A',
  'Long-Term Debt': 'N/A',
  'Shareholders’ Equity': '35,700,000',
  'Dividends Paid': 'N/A',
  'Number of Outstanding Shares': 'N/A',
  'Guidance/Forecast': 'N/A',
  'Key Performance Indicators (KPIs)': 'N/A'},
 {'Company Name': 'Retailors Ltd.',
  'Report Date': 'March 31, 2021',
  'Revenue': '173,103,000',
  'Net Income': '-11,682,000',
  'Earnings Per Share (EPS)': '-34.19',
  'Gross Profit': '82,722,000',
  'Operating Income (EBIT)': '12,221,000',
  'Operating Cash Flow': 'N/A',
  'Investing Cash Flow': 'N/A',
  'Financing Cash Flow': 'N/A',
  'Total Assets': '1,243,521,000',
  'Total Liabilities': '1,181,349,000',
  'Short-Term Debt': '111,166,000',
  'Long-Term Debt': '32,317,000',
  'Shareholders’ Equity': '62,172,000',
  'Dividends Paid': 'N/A',
  'Number of Outstanding Shares': 'N/A',
  'Guidance/Forecast': 'N/A',
  'Key Performance Indicators (KPIs)': 'Sales in identical stores Nike 1-3 2021: 94.2%\nSales in identical stores Foot Locker 1-3 2021: 133.8%'},
 [{'Company Name': 'PMS Migan Ltd.',
   'Report Date': 'March 31, 2021',
   'Revenue': '21,274,000',
   'Net Income': '5,502,000',
   'Earnings Per Share (EPS)': '0.60',
   'Gross Profit': '8,958,000',
   'Operating Income (EBIT)': '6,898,000',
   'Operating Cash Flow': '5,512,000',
   'Investing Cash Flow': '-4,773,000',
   'Financing Cash Flow': '-33,000',
   'Total Assets': '125,160,000',
   'Total Liabilities': '26,190,000',
   'Short-Term Debt': 'N/A',
   'Long-Term Debt': 'N/A',
   'Shareholders’ Equity': '98,970,000',
   'Dividends Paid': 'N/A',
   'Number of Outstanding Shares': 'N/A',
   'Guidance/Forecast': "The company's estimates as described above that the increase in sales and the increase in the number and scope of orders received by the company stems from a trend of some recovery from the effects of the virus constitutes forward-looking information, as defined in the Securities Law, 1968. This information is based on the company's management's assessments based on past experience, as well as based on conversations and contacts with its customers. This information may not materialize or materialize in a different way (even substantially).",
   'Key Performance Indicators (KPIs)': 'N/A'}],
 {'Company Name': 'Madrin LTD',
  'Report Date': 'March 31, 2021',
  'Revenue': '411,165,000',
  'Net Income': '28,289,000',
  'Earnings Per Share (EPS)': '14.37',
  'Gross Profit': '57,849,000',
  'Operating Income (EBIT)': '51,749,000',
  'Operating Cash Flow': '87,441,000',
  'Investing Cash Flow': '23,711,000',
  'Financing Cash Flow': '38,243,000',
  'Total Assets': '710,694,000',
  'Total Liabilities': '218,691,000',
  'Short-Term Debt': 'N/A',
  'Long-Term Debt': '118,381,000',
  'Shareholders’ Equity': '604,834,000',
  'Dividends Paid': 'N/A',
  'Number of Outstanding Shares': 'N/A',
  'Guidance/Forecast': 'N/A',
  'Key Performance Indicators (KPIs)': 'EBITDA 64,501,000'},
 [{'Company Name': 'Inrom Industries',
   'Report Date': '2021-03-31',
   'Revenue': '245,462,000',
   'Net Income': '27,164,000',
   'Earnings Per Share (EPS)': '0.22',
   'Gross Profit': '91,657,000',
   'Operating Income (EBIT)': '38,155,000',
   'Operating Cash Flow': '40,336,000',
   'Investing Cash Flow': '-9,264,000',
   'Financing Cash Flow': '-90,990,000',
   'Total Assets': '971,066,000',
   'Total Liabilities': '483,864,000',
   'Short-Term Debt': '54,809,000',
   'Long-Term Debt': '64,179,000',
   'Shareholders’ Equity': '483,864,000',
   'Dividends Paid': '7,626,000',
   'Number of Outstanding Shares': 'N/A',
   'Guidance/Forecast': 'N/A',
   'Key Performance Indicators (KPIs)': 'N/A'},
  {'Company Name': 'Inrom Industries',
   'Report Date': '2021-03-31',
   'Revenue': 'N/A',
   'Net Income': 'N/A',
   'Earnings Per Share (EPS)': 'N/A',
   'Gross Profit': 'N/A',
   'Operating Income (EBIT)': 'N/A',
   'Operating Cash Flow': 'N/A',
   'Investing Cash Flow': 'N/A',
   'Financing Cash Flow': 'N/A',
   'Total Assets': '425,141,000',
   'Total Liabilities': 'N/A',
   'Short-Term Debt': 'N/A',
   'Long-Term Debt': 'N/A',
   'Shareholders’ Equity': '410,173,000',
   'Dividends Paid': 'N/A',
   'Number of Outstanding Shares': 'N/A',
   'Guidance/Forecast': 'N/A',
   'Key Performance Indicators (KPIs)': 'N/A'}],
 [{'Company Name': 'Elad Israel Residences Ltd.',
   'Report Date': 'March 31, 2021',
   'Revenue': '98,768,000',
   'Net Income': '10,067,000',
   'Earnings Per Share (EPS)': 'N/A',
   'Gross Profit': '24,654,000',
   'Operating Income (EBIT)': '15,872,000',
   'Operating Cash Flow': '21,517,000',
   'Investing Cash Flow': '-14,474,000',
   'Financing Cash Flow': '-197,000',
   'Total Assets': '816,536,000',
   'Total Liabilities': '543,788,000',
   'Short-Term Debt': '295,341,000',
   'Long-Term Debt': '80,305,000',
   'Shareholders’ Equity': '282,815,000',
   'Dividends Paid': 'N/A',
   'Number of Outstanding Shares': 'N/A',
   'Guidance/Forecast': 'N/A',
   'Key Performance Indicators (KPIs)': 'N/A'}],
 {'Company Name': 'Energean plc',
  'Report Date': 'May 24, 2021',
  'Revenue': '94,900,000',
  'Net Income': 'N/A',
  'Earnings Per Share (EPS)': 'N/A',
  'Gross Profit': 'N/A',
  'Operating Income (EBIT)': 'N/A',
  'Operating Cash Flow': 'N/A',
  'Investing Cash Flow': 'N/A',
  'Financing Cash Flow': 'N/A',
  'Total Assets': 'N/A',
  'Total Liabilities': 'N/A',
  'Short-Term Debt': 'N/A',
  'Long-Term Debt': 'N/A',
  'Shareholders’ Equity': 'N/A',
  'Dividends Paid': 'N/A',
  'Number of Outstanding Shares': 'N/A',
  'Guidance/Forecast': '2021 year-end net debt guidance reduced to between 1,900,000,000 and 2,000,000,000',
  'Key Performance Indicators (KPIs)': 'Production in the four-months to 30 April 2021 was 44.2 kboepd (72% gas), guidance increased to 38,000 – 42,000 kboepd (from 36,000 – 41,000 kboepd). First production from Karish now expected in mid-2022.'},
 {'Company Name': 'EMET E&M COMPUTING',
  'Report Date': '31.3.2021',
  'Revenue': '391,525,000',
  'Net Income': '12,784,000',
  'Earnings Per Share (EPS)': '0.281',
  'Gross Profit': '64,278,000',
  'Operating Income (EBIT)': '20,378,000',
  'Operating Cash Flow': 'N/A',
  'Investing Cash Flow': 'N/A',
  'Financing Cash Flow': 'N/A',
  'Total Assets': '882,232,000',
  'Total Liabilities': '474,161,000',
  'Short-Term Debt': 'N/A',
  'Long-Term Debt': 'N/A',
  'Shareholders’ Equity': '308,030,000',
  'Dividends Paid': '9,085,000',
  'Number of Outstanding Shares': 'N/A',
  'Guidance/Forecast': 'N/A',
  'Key Performance Indicators (KPIs)': 'EBITDA : 28,047,000'},
 {'Company Name': 'Bet Shemesh Engines Holdings (1997) LTD.',
  'Report Date': 'March 31, 2021',
  'Revenue': '28,557,000',
  'Net Income': '-963,000',
  'Earnings Per Share (EPS)': '-0.11',
  'Gross Profit': '1,047,000',
  'Operating Income (EBIT)': '-1,010,000',
  'Operating Cash Flow': '3,770,000',
  'Investing Cash Flow': '-2,043,000',
  'Financing Cash Flow': '-2,468,000',
  'Total Assets': '261,413,000',
  'Total Liabilities': '131,984,000',
  'Short-Term Debt': '38,868,000',
  'Long-Term Debt': '44,631,000',
  'Shareholders’ Equity': '131,955,000',
  'Dividends Paid': 'N/A',
  'Number of Outstanding Shares': 'N/A',
  'Guidance/Forecast': 'N/A',
  'Key Performance Indicators (KPIs)': 'N/A'},
 {'Company Name': 'Zim Urban by Rani Zim',
  'Report Date': 'March 31, 2021',
  'Revenue': 'N/A',
  'Net Income': 'N/A',
  'Earnings Per Share (EPS)': 'N/A',
  'Gross Profit': 'N/A',
  'Operating Income (EBIT)': 'N/A',
  'Operating Cash Flow': 'N/A',
  'Investing Cash Flow': 'N/A',
  'Financing Cash Flow': 'N/A',
  'Total Assets': '1,420,116 thousands ILS',
  'Total Liabilities': '948,364 thousands ILS',
  'Short-Term Debt': 'N/A',
  'Long-Term Debt': 'N/A',
  'Shareholders’ Equity': '478,713 thousands ILS',
  'Dividends Paid': 'N/A',
  'Number of Outstanding Shares': 'N/A',
  'Guidance/Forecast': 'N/A',
  'Key Performance Indicators (KPIs)': 'N/A'},
 {'Company Name': 'MICRONET',
  'Report Date': '31.03.2021',
  'Revenue': '2,372,000',
  'Net Income': '-2,662,000',
  'Earnings Per Share (EPS)': 'N/A',
  'Gross Profit': '31,000',
  'Operating Income (EBIT)': '-2,391,000',
  'Operating Cash Flow': '-1,528,000',
  'Investing Cash Flow': '-420,000',
  'Financing Cash Flow': '-676,000',
  'Total Assets': '21,268,000',
  'Total Liabilities': '12,536,000',
  'Short-Term Debt': '2,199,000',
  'Long-Term Debt': '496,000',
  'Shareholders’ Equity': '8,127,000',
  'Dividends Paid': 'N/A',
  'Number of Outstanding Shares': 'N/A',
  'Guidance/Forecast': "The company expects that demands in the market will translate into further significant orders. The company continues to accelerate business efforts, with an emphasis on sales, the operational adjustments required to accelerate the company's serial production capacity, and the advancement of negotiations with leading new and existing customers toward signing contracts.",
  'Key Performance Indicators (KPIs)': 'Current Ratio: 1.51 \nQuick Ratio: 0.99'},
 [{'Company Name': 'Ness Ziona Properties and Buildings Ltd',
   'Report Date': 'March 31, 2021',
   'Revenue': 'N/A',
   'Net Income': 'N/A',
   'Earnings Per Share (EPS)': 'N/A',
   'Gross Profit': 'N/A',
   'Operating Income (EBIT)': 'N/A',
   'Operating Cash Flow': 'N/A',
   'Investing Cash Flow': 'N/A',
   'Financing Cash Flow': 'N/A',
   'Total Assets': '7,967,000,000',
   'Total Liabilities': '6,223,000,000',
   'Short-Term Debt': '1,250,000,000',
   'Long-Term Debt': '4,973,000,000',
   'Shareholders’ Equity': '1,744,000,000',
   'Dividends Paid': 'N/A',
   'Number of Outstanding Shares': 'N/A',
   'Guidance/Forecast': 'N/A',
   'Key Performance Indicators (KPIs)': 'Occupancy rate of 92.5%'},
  {'Company Name': 'IDB Group USA Investments Inc.',
   'Report Date': 'March 31, 2021',
   'Revenue': '3,305,000',
   'Net Income': '-703,000',
   'Earnings Per Share (EPS)': 'N/A',
   'Gross Profit': 'N/A',
   'Operating Income (EBIT)': 'N/A',
   'Operating Cash Flow': '1,658,000',
   'Investing Cash Flow': '-247,000',
   'Financing Cash Flow': '-1,332,000',
   'Total Assets': '249,821,000',
   'Total Liabilities': '249,821,000',
   'Short-Term Debt': '130,506,000',
   'Long-Term Debt': '119,315,000',
   'Shareholders’ Equity': 'N/A',
   'Dividends Paid': 'N/A',
   'Number of Outstanding Shares': 'N/A',
   'Guidance/Forecast': 'N/A',
   'Key Performance Indicators (KPIs)': 'N/A'}],
 {'Company Name': 'Rotshtein Real Estate Ltd.',
  'Report Date': 'March 31, 2021',
  'Revenue': 'N/A',
  'Net Income': '49,580,000',
  'Earnings Per Share (EPS)': '3.71',
  'Gross Profit': '63,651,000',
  'Operating Income (EBIT)': '77,016,000',
  'Operating Cash Flow': 'N/A',
  'Investing Cash Flow': 'N/A',
  'Financing Cash Flow': 'N/A',
  'Total Assets': '1,160,428,000',
  'Total Liabilities': '942,838,000',
  'Short-Term Debt': 'N/A',
  'Long-Term Debt': 'N/A',
  'Shareholders’ Equity': '173,389,000',
  'Dividends Paid': '8,000,000',
  'Number of Outstanding Shares': 'N/A',
  'Guidance/Forecast': 'N/A',
  'Key Performance Indicators (KPIs)': 'N/A'},
 {'Company Name': 'Magurit Israel Ltd.',
  'Report Date': 'May 23, 2021',
  'Revenue': 'N/A',
  'Net Income': '-5,094,000',
  'Earnings Per Share (EPS)': '-0.05',
  'Gross Profit': 'N/A',
  'Operating Income (EBIT)': 'N/A',
  'Operating Cash Flow': 'N/A',
  'Investing Cash Flow': 'N/A',
  'Financing Cash Flow': 'N/A',
  'Total Assets': '2,203,799,000',
  'Total Liabilities': '1,251,410,000',
  'Short-Term Debt': '111,245,000',
  'Long-Term Debt': '1,125,651,000',
  'Shareholders’ Equity': '833,350,000',
  'Dividends Paid': 'N/A',
  'Number of Outstanding Shares': 'N/A',
  'Guidance/Forecast': 'N/A',
  'Key Performance Indicators (KPIs)': 'N/A'},
 [{'Company Name': 'Magurite Israel',
   'Report Date': '25.4.2021',
   'Revenue': 'N/A',
   'Net Income': 'N/A',
   'Earnings Per Share (EPS)': 'N/A',
   'Gross Profit': 'N/A',
   'Operating Income (EBIT)': 'N/A',
   'Operating Cash Flow': 'N/A',
   'Investing Cash Flow': 'N/A',
   'Financing Cash Flow': 'N/A',
   'Total Assets': 'N/A',
   'Total Liabilities': 'N/A',
   'Short-Term Debt': 'N/A',
   'Long-Term Debt': 'N/A',
   'Shareholders’ Equity': 'N/A',
   'Dividends Paid': 'N/A',
   'Number of Outstanding Shares': 'N/A',
   'Guidance/Forecast': 'N/A',
   'Key Performance Indicators (KPIs)': 'N/A'},
  {'Company Name': 'Magurite Israel',
   'Report Date': '28.4.2021',
   'Revenue': 'N/A',
   'Net Income': 'N/A',
   'Earnings Per Share (EPS)': 'N/A',
   'Gross Profit': 'N/A',
   'Operating Income (EBIT)': 'N/A',
   'Operating Cash Flow': 'N/A',
   'Investing Cash Flow': 'N/A',
   'Financing Cash Flow': 'N/A',
   'Total Assets': 'N/A',
   'Total Liabilities': 'N/A',
   'Short-Term Debt': 'N/A',
   'Long-Term Debt': 'N/A',
   'Shareholders’ Equity': 'N/A',
   'Dividends Paid': 'N/A',
   'Number of Outstanding Shares': 'N/A',
   'Guidance/Forecast': 'N/A',
   'Key Performance Indicators (KPIs)': 'N/A'},
  {'Company Name': 'Magurite Israel',
   'Report Date': '28.4.2021',
   'Revenue': 'N/A',
   'Net Income': 'N/A',
   'Earnings Per Share (EPS)': 'N/A',
   'Gross Profit': 'N/A',
   'Operating Income (EBIT)': 'N/A',
   'Operating Cash Flow': 'N/A',
   'Investing Cash Flow': 'N/A',
   'Financing Cash Flow': 'N/A',
   'Total Assets': 'N/A',
   'Total Liabilities': 'N/A',
   'Short-Term Debt': 'N/A',
   'Long-Term Debt': 'N/A',
   'Shareholders’ Equity': 'N/A',
   'Dividends Paid': 'N/A',
   'Number of Outstanding Shares': 'N/A',
   'Guidance/Forecast': 'N/A',
   'Key Performance Indicators (KPIs)': 'N/A'},
  {'Company Name': 'Magurite Israel',
   'Report Date': '28.4.2021',
   'Revenue': 'N/A',
   'Net Income': 'N/A',
   'Earnings Per Share (EPS)': 'N/A',
   'Gross Profit': 'N/A',
   'Operating Income (EBIT)': 'N/A',
   'Operating Cash Flow': 'N/A',
   'Investing Cash Flow': 'N/A',
   'Financing Cash Flow': 'N/A',
   'Total Assets': 'N/A',
   'Total Liabilities': 'N/A',
   'Short-Term Debt': 'N/A',
   'Long-Term Debt': 'N/A',
   'Shareholders’ Equity': 'N/A',
   'Dividends Paid': 'N/A',

### Data Loading & Initial Cleaning

This function dynamically loads quarterly financial report JSON files from Google Drive, flattens nested structures, and cleans the numeric columns by removing formatting and converting values to floats. It ensures consistency across reports by standardizing the parameters per file into columns and preserving key textual fields for further processing.

In [43]:


def load_and_clean_financial_report(year: int, quarter: str):
    # Step 1: Build the file path dynamically
    path = f"/content/drive/Shareddrives/capstone project-stock market robo-advisor/Reports Parameters/financial_reports_{quarter}_{year}.json"

    # Step 2: Load JSON
    with open(path, 'r', encoding='utf-8') as f:
        raw_data = json.load(f)

    # Step 3: Flatten list of lists
    flattened_data = []
    for item in raw_data:
        if isinstance(item, list):
            flattened_data.extend(item)
        else:
            flattened_data.append(item)

    # Step 4: Convert to DataFrame
    df = pd.DataFrame(flattened_data)

    # Step 5: Keep only first 19 columns
    df = df.iloc[:, :19]

    # Step 6: Replace 'N/A' with NaN
    df = df.replace('N/A', np.nan)

    # Step 7: Clean all columns except for preserved string ones
    string_columns = ['Company Name', 'Report Date', 'Guidance/Forecast']

    for col in df.columns:
        if col not in string_columns:
            # Clean number formatting and convert to float
            df[col] = (
                df[col]
                .astype(str)
                .str.replace(',', '', regex=False)
                .str.replace(r'\((.*?)\)', r'-\1', regex=True)
            )
            df[col] = pd.to_numeric(df[col], errors='coerce')

    # Step 8: Dynamically name the DataFrame
    var_name = f"financial_reports_{quarter}_{year}"
    globals()[var_name] = df
    return df

In [44]:
df2021_q1 = load_and_clean_financial_report(2021, "q1")

In [45]:
df2021_q1

,Company Name,Report Date,Revenue,Net Income,Earnings Per Share (EPS),Gross Profit,Operating Income (EBIT),Operating Cash Flow,Investing Cash Flow,Financing Cash Flow,Total Assets,Total Liabilities,Short-Term Debt,Long-Term Debt,Shareholders’ Equity,Dividends Paid,Number of Outstanding Shares,Guidance/Forecast,Key Performance Indicators (KPIs)
0,Tel Aviv Stock Exchange,"March 31, 2021",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.903880e+08,265772000.0,NaN,NaN,624616000.0,18450000.0,NaN,NaN,NaN
1,S.N. Shnepp & Sons Ltd.,"March 31, 2021",4.153700e+08,29917000.0,1.78,108080000.0,41995000.0,NaN,NaN,NaN,5.138160e+08,200165000.0,NaN,NaN,307939000.0,10000000.0,NaN,NaN,NaN
2,Golan Plastic Products Ltd,"March 31, 2021",8.331000e+07,28681000.0,0.86,24972000.0,11974000.0,47095000.0,-30151000.0,-10281000.0,4.461790e+08,231531000.0,33800000.0,28966000.0,224978000.0,NaN,NaN,NaN,NaN
3,Orian S.M. Ltd.,"March 31, 2021",6.494000e+07,4135000.0,0.21,5510000.0,2432000.0,15264000.0,-32820000.0,30678000.0,3.019750e+08,225363000.0,8103000.0,33409000.0,76612000.0,NaN,13556686.0,NaN,NaN
4,Bikurei Sadeh (Holdings),"March 31, 2021",1.175232e+09,99133000.0,0.84,288159000.0,109095000.0,52850000.0,-20003000.0,-39082000.0,8.326480e+08,261531000.0,163594000.0,261531000.0,85381000.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
423,The First International Bank Issues Ltd,"March 31, 2021",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,735000000.0,NaN,NaN,NaN,NaN
424,Bank Otsar Hahayal Ltd,"March 31, 2021",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8000000.0,NaN,NaN,NaN,NaN
425,Bank Otsar Hahayal Ltd,"March 31, 2021",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2000000.0,NaN,NaN,NaN,NaN
426,Bank Otsar Hahayal Ltd,"March 31, 2021",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,66000000.0,NaN,NaN,NaN,NaN
427,Maytronics,"March 31, 2021",4.190790e+08,91303000.0,0.80,182277000.0,112255000.0,NaN,NaN,NaN,1.272033e+09,740143000.0,191694000.0,53777000.0,499179000.0,45000000.0,NaN,NaN,NaN

### Fuzzy Matching for Company Name Unification

This section uses fuzzy string matching to automatically group and unify variations of company names that refer to the same entity. It selects the most complete row (fewest missing values) from each group and assigns a canonical name, reducing redundancy in the dataset.

In [46]:


def auto_group_similar_names(df, threshold=80):
    company_names = df['Company Name'].dropna().unique()
    grouped = defaultdict(list)
    used = set()

    for name in company_names:
        if name in used:
            continue
        # Find close matches
        matches = process.extract(name, company_names, scorer=fuzz.token_sort_ratio)
        group = [match for match, score, _ in matches if score >= threshold]
        for match in group:
            used.add(match)
        grouped[name].extend(group)

    return grouped

def unify_companies_by_fuzzy_match(df, threshold=80):
    name_mapping = auto_group_similar_names(df, threshold)
    unified_rows = []

    for canonical_name, variations in name_mapping.items():
        subset = df[df['Company Name'].isin(variations)]
        if subset.empty:
            continue
        unified = subset.bfill().iloc[0]
        unified['Company Name'] = canonical_name
        unified_rows.append(unified)

    return pd.DataFrame(unified_rows)

# 👇 Run this
df_unified = unify_companies_by_fuzzy_match(df2021_q1, threshold=80)

<ipython-input-46-5c3039ff3f2b>:26: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  unified = subset.bfill().iloc[0]

In [47]:
df_unified

,Company Name,Report Date,Revenue,Net Income,Earnings Per Share (EPS),Gross Profit,Operating Income (EBIT),Operating Cash Flow,Investing Cash Flow,Financing Cash Flow,Total Assets,Total Liabilities,Short-Term Debt,Long-Term Debt,Shareholders’ Equity,Dividends Paid,Number of Outstanding Shares,Guidance/Forecast,Key Performance Indicators (KPIs)
0,Tel Aviv Stock Exchange,"March 31, 2021",7.840000e+07,9661000.0,0.093,NaN,NaN,41800000.0,-14700000.0,-2300000.0,8.903880e+08,265772000.0,NaN,NaN,624616000.0,18450000.0,NaN,NaN,NaN
1,S.N. Shnepp & Sons Ltd.,"March 31, 2021",4.153700e+08,29917000.0,1.780,108080000.0,41995000.0,NaN,NaN,NaN,5.138160e+08,200165000.0,NaN,NaN,307939000.0,10000000.0,NaN,NaN,NaN
2,Golan Plastic Products Ltd,"March 31, 2021",8.331000e+07,28681000.0,0.860,24972000.0,11974000.0,47095000.0,-30151000.0,-10281000.0,4.461790e+08,231531000.0,33800000.0,28966000.0,224978000.0,NaN,NaN,NaN,NaN
3,Orian S.M. Ltd.,"March 31, 2021",6.494000e+07,4135000.0,0.210,5510000.0,2432000.0,15264000.0,-32820000.0,30678000.0,3.019750e+08,225363000.0,8103000.0,33409000.0,76612000.0,NaN,13556686.0,NaN,NaN
4,Bikurei Sadeh (Holdings),"March 31, 2021",1.175232e+09,99133000.0,0.840,288159000.0,109095000.0,52850000.0,-20003000.0,-39082000.0,8.326480e+08,261531000.0,163594000.0,261531000.0,85381000.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
412,BioView Ltd.,"March 31, 2021",7.435000e+06,884000.0,0.060,4028000.0,NaN,730000.0,-313000.0,-1600000.0,3.388900e+07,8820000.0,NaN,NaN,25069000.0,NaN,NaN,NaN,NaN
414,Aylon Bituach Hanpakot Vegiusi Hon LTD,"March 31, 2021",3.906000e+06,-1071000.0,NaN,NaN,NaN,-24000.0,NaN,NaN,1.237850e+08,110139000.0,1467000.0,108672000.0,13646000.0,NaN,NaN,NaN,NaN
415,The First International Bank of Israel Ltd,"March 31, 2021",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,927000000.0,NaN,NaN,NaN,NaN
424,Bank Otsar Hahayal Ltd,"March 31, 2021",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8000000.0,NaN,NaN,NaN,NaN
427,Maytronics,"March 31, 2021",4.190790e+08,91303000.0,0.800,182277000.0,112255000.0,NaN,NaN,NaN,1.272033e+09,740143000.0,191694000.0,53777000.0,499179000.0,45000000.0,NaN,NaN,NaN

In [48]:


# Load the mapping Excel file (ticker → company name)
mapping_path = "/content/drive/Shareddrives/capstone project-stock market robo-advisor/Noam's work/Best model per stock/Helpful files /company_name_to_ticker.xlsx"
mapping_df = pd.read_excel(mapping_path)
company_map = mapping_df[['Ticker', 'CompanyName']].dropna()
reference_names = company_map['CompanyName'].str.upper().unique().tolist()

# Manual name override dictionary
manual_name_map = {
    k.upper(): v.upper()
    for k, v in {
        "A. Luzon Real Estate and Finance": "LUZON GROUP",
        "Alon Blue Square Israel": "BLUE SQUARE REAL ESTATE",
        "Accel Solutions Group": "ACCEL",
        "Electreon Wireless": "ELECTREON",
        "El Al Israel Airlines.": "EL AL",
        "Elbit Medical Technologies": "ELBIT MEDITEC",
        "Enlight Renewable Energy": "ENLIGHT ENERGY",
        "Enlivex Therapeutics": "ENLIVEX",
        "Alony Hetz Properties and Investments": "ALONY HETZ",
        "Aylon Bituach Hanpakot Vegiusi Hon LTD": "AYALON HOLD.",
        "Avgol Industries 1953": "AVGOL",
        "Bet Shemesh Engines Holdings (1997) LTD.": "BET SHEMESH",
        "Bicuri Sadeh": "BIKUREY HASHDE",
        "Bikurei Sadeh (Holdings)": "BIKUREY HASHDE",
        "Biolight Life Sciences": "BIOLIGHT",
        "C.I. Systems (Israel)": "C I SYSTEMS",
        "Cellcom Israel": "CELLCOM",
        "Clal Insurance Enterprises Holdings": "CLAL INSURANCE",
        "Delek Motors Vehicle Systems": "DELEK AUTOMOTIV"

    }.items()
}

GENERIC_SUFFIXES = ['HOLDINGS', 'INVESTMENTS', 'PROPERTIES', 'GROUP', 'REAL ESTATE', 'COMPANY', 'PROPERTIES AND INVESTMENTS', 'SOLUTIONS GROUP',
                    'LIFE SCIENCES','REAL ESTATE', 'REAL ESTATE AND FINANCE', 'INDUSTRIAL DEVELOPMENT', 'ENGINEERING','COMPUTING', 'INTERNET']

def generate_variants(name: str):
    """
    Generate multiple variants of a cleaned name:
    - base form
    - base + each generic suffix
    - base - each generic word (if it exists)
    """
    base = clean_name(name)
    variants = set([base])

    # If base already contains suffixes, try removing them
    words = base.split()
    without_suffix = ' '.join([w for w in words if w not in GENERIC_SUFFIXES])
    variants.add(without_suffix)

    # Try adding common suffixes
    for suffix in GENERIC_SUFFIXES:
        variants.add(f"{base} {suffix}")
        variants.add(f"{without_suffix} {suffix}")

    return variants


# Clean helper
def clean_name(name: str) -> str:
    name = name.upper()
    name = re.sub(r'\b(LTD.|INC|LTD|CORP|LIMITED|\.|,|\&)\b', '', name)
    name = re.sub(r'\s+', ' ', name).strip()
    return name

# Fuzzy matcher using cleaned names
def match_company_name_fuzzy(name: str, reference_names, threshold=85):
    # 1. Manual override first
    name_cleaned = clean_name(name)
    if name_cleaned in manual_name_map:
        return manual_name_map[name_cleaned]

    # 2. Clean all reference names into a searchable map
    ref_cleaned_map = {clean_name(ref): ref for ref in reference_names}

    # 3. Try all name variants
    name_variants = generate_variants(name)
    best_match, best_score = None, -1

    for variant in name_variants:
        match, score, _ = process.extractOne(variant, list(ref_cleaned_map.keys()), scorer=fuzz.token_sort_ratio)
        if score > best_score and score >= threshold:
            best_score = score
            best_match = ref_cleaned_map[match]

    return best_match


# Apply to your unified DataFrame
def standardize_company_names(df, reference_names, threshold=85):
    updated = []
    df["Company Name"] = df["Company Name"].str.replace(r"\s*Ltd\.?", "", regex=True).str.strip()
    df["Company Name"] = df["Company Name"].str.replace(r"Bank", "", regex=True).str.strip()


    for original in df['Company Name']:
        match = match_company_name_fuzzy(original, reference_names, threshold)
        updated_name = match if match else original  # use original if no match
        updated.append(updated_name)

    df = df.copy()
    df['Company Name'] = updated
    return df

# 👇 Run this on df_unified
df_final = standardize_company_names(df_unified, reference_names, threshold = 85)

# # Optional: Save to file
# output_path = "/content/drive/MyDrive/df_financial_reports_q1_2023_full_names.csv"
# df_final.to_csv(output_path, index=False)
# print("✅ Cleaned DataFrame saved to:", output_path)

In [49]:
df_final

,Company Name,Report Date,Revenue,Net Income,Earnings Per Share (EPS),Gross Profit,Operating Income (EBIT),Operating Cash Flow,Investing Cash Flow,Financing Cash Flow,Total Assets,Total Liabilities,Short-Term Debt,Long-Term Debt,Shareholders’ Equity,Dividends Paid,Number of Outstanding Shares,Guidance/Forecast,Key Performance Indicators (KPIs)
0,Tel Aviv Stock Exchange,"March 31, 2021",7.840000e+07,9661000.0,0.093,NaN,NaN,41800000.0,-14700000.0,-2300000.0,8.903880e+08,265772000.0,NaN,NaN,624616000.0,18450000.0,NaN,NaN,NaN
1,S.N. Shnepp & Sons,"March 31, 2021",4.153700e+08,29917000.0,1.780,108080000.0,41995000.0,NaN,NaN,NaN,5.138160e+08,200165000.0,NaN,NaN,307939000.0,10000000.0,NaN,NaN,NaN
2,Golan Plastic Products,"March 31, 2021",8.331000e+07,28681000.0,0.860,24972000.0,11974000.0,47095000.0,-30151000.0,-10281000.0,4.461790e+08,231531000.0,33800000.0,28966000.0,224978000.0,NaN,NaN,NaN,NaN
3,Orian S.M.,"March 31, 2021",6.494000e+07,4135000.0,0.210,5510000.0,2432000.0,15264000.0,-32820000.0,30678000.0,3.019750e+08,225363000.0,8103000.0,33409000.0,76612000.0,NaN,13556686.0,NaN,NaN
4,BIKUREY HASHDE,"March 31, 2021",1.175232e+09,99133000.0,0.840,288159000.0,109095000.0,52850000.0,-20003000.0,-39082000.0,8.326480e+08,261531000.0,163594000.0,261531000.0,85381000.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
412,BIO VIEW,"March 31, 2021",7.435000e+06,884000.0,0.060,4028000.0,NaN,730000.0,-313000.0,-1600000.0,3.388900e+07,8820000.0,NaN,NaN,25069000.0,NaN,NaN,NaN,NaN
414,Aylon Bituach Hanpakot Vegiusi Hon LTD,"March 31, 2021",3.906000e+06,-1071000.0,NaN,NaN,NaN,-24000.0,NaN,NaN,1.237850e+08,110139000.0,1467000.0,108672000.0,13646000.0,NaN,NaN,NaN,NaN
415,The First International of Israel,"March 31, 2021",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,927000000.0,NaN,NaN,NaN,NaN
424,Otsar Hahayal,"March 31, 2021",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8000000.0,NaN,NaN,NaN,NaN
427,MAYTRONICS,"March 31, 2021",4.190790e+08,91303000.0,0.800,182277000.0,112255000.0,NaN,NaN,NaN,1.272033e+09,740143000.0,191694000.0,53777000.0,499179000.0,45000000.0,NaN,NaN,NaN

### Standardizing Company Names via Mapping and Fuzzy Variants

This stage refines company names by matching them to official names from a ticker mapping Excel file using both a manual override dictionary and a robust fuzzy matching system. It generates multiple name variants (e.g., with/without suffixes) and uses token-based similarity scoring to find the best match. This ensures alignment between report names and official tickers, which is crucial for downstream financial analysis.

In [50]:

# Load mapping Excel (already loaded earlier as mapping_df)
mapping_df = pd.read_excel(mapping_path)
mapping_df = mapping_df[['CompanyName', 'Ticker', 'JsonNames']].fillna("")

# Build alias dictionary: maps every known JSON name to the official CompanyName
json_name_to_real = {}

for _, row in mapping_df.iterrows():
    real_name = str(row['CompanyName']).strip()
    json_names = row['JsonNames']

    aliases = set()

    # Try parsing as a list of names
    if isinstance(json_names, str):
        try:
            parsed = ast.literal_eval(json_names)
            if isinstance(parsed, list):
                aliases.update([x.strip().upper() for x in parsed])
            else:
                aliases.add(json_names.strip().upper())
        except:
            aliases.add(json_names.strip().upper())

    # Add mapping from each alias to the official company name
    for alias in aliases:
        if alias:
            json_name_to_real[alias] = real_name.upper()

    # Also map the official name to itself
    json_name_to_real[real_name.upper()] = real_name.upper()

# Now apply the mapping to the unified DataFrame
unified_df = df_unified.copy()
unified_df['Company Name'] = unified_df['Company Name'].astype(str).str.strip()

standardized_rows = []
not_found = []

grouped = unified_df.groupby('Company Name')

for name, group in grouped:
    key = name.strip().upper()

    # Step 1: Try to find matching canonical name
    if key in json_name_to_real:
        real_name = json_name_to_real[key]
    else:
        not_found.append(name)
        standardized_rows.append(group.iloc[0])  # keep as-is
        continue

    # Step 2: Get all rows corresponding to this real name
    aliases = [k for k, v in json_name_to_real.items() if v == real_name]
    matching_rows = unified_df[unified_df['Company Name'].str.upper().isin(aliases)]

    # Step 3: Merge info – use row with fewest NaNs
    merged_row = matching_rows.loc[matching_rows.isna().sum(axis=1).idxmin()].copy()
    merged_row['Company Name'] = real_name
    standardized_rows.append(merged_row)

# Final result
df_final_cleaned = pd.DataFrame(standardized_rows).reset_index(drop=True)

df_final_cleaned

,Company Name,Report Date,Revenue,Net Income,Earnings Per Share (EPS),Gross Profit,Operating Income (EBIT),Operating Cash Flow,Investing Cash Flow,Financing Cash Flow,Total Assets,Total Liabilities,Short-Term Debt,Long-Term Debt,Shareholders’ Equity,Dividends Paid,Number of Outstanding Shares,Guidance/Forecast,Key Performance Indicators (KPIs)
0,LUZON GROUP,"March 31, 2021",NaN,-671000.00,-0.420,NaN,NaN,-2.738000e+06,922000.00,2.123000e+06,1.196170e+08,3.746600e+07,1.372500e+07,3.500000e+05,8.180100e+07,NaN,NaN,NaN,NaN
1,ADAMA Agricultural Solutions,"March 31, 2021",1.020000e+09,34000000.00,NaN,285000000.0,76000000.00,-1.170000e+08,-73000000.00,2.361120e+08,6.200215e+09,3.727711e+09,5.381044e+08,1.419233e+09,2.473000e+09,NaN,137990881.0,NaN,NaN
2,ARKO Corp.,"March 31, 2021",1.484356e+09,-14662000.00,-0.130,NaN,13239000.00,1.127600e+07,-16645000.00,-8.314300e+07,2.650554e+09,2.371232e+09,2.949500e+07,6.447640e+08,1.794690e+08,NaN,124428000.0,NaN,NaN
3,ACCEL,"March 31, 2021",2.117600e+07,297000.00,0.001,4179000.0,NaN,-4.652000e+06,-8180000.00,2.013500e+07,1.296330e+08,7.807100e+07,6.080000e+05,1.316000e+06,6.890500e+07,NaN,NaN,NaN,NaN
4,Ace Capital Retail (2016),"March 31, 2021",1.794160e+08,8532000.00,0.370,80074000.0,14356000.00,NaN,NaN,NaN,8.122480e+08,6.703890e+08,NaN,NaN,1.418590e+08,20300000.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
350,"Zhuhai ACCESS Semiconductor Co.,","March 31, 2021",2.974263e+08,36510319.75,NaN,NaN,38801318.25,4.614806e+07,-21847834.12,2.460594e+07,2.013603e+09,9.868398e+08,7.397944e+07,4.394626e+08,1.026763e+09,NaN,694810165.0,NaN,NaN
351,Zim Urban by Rani Zim,"March 31, 2021",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
352,Ziviel Investments,"March 31, 2021",1.906000e+07,-1595000.00,NaN,4438000.0,4438000.00,1.119700e+07,-106000.00,-6.061000e+06,3.761870e+08,2.564340e+08,1.258000e+07,1.838720e+08,1.197530e+08,NaN,NaN,NaN,NaN
353,ZUR,"March 31, 2021",NaN,NaN,NaN,NaN,NaN,5.410500e+08,76227000.00,8.118320e+08,1.529148e+10,8.154560e+09,NaN,NaN,1.802194e+09,8000000.0,64954008.0,NaN,NaN
354,Zvi Zarfati & Sons Investments and Building 1992,"March 31, 2021",5.800000e+07,5500000.00,0.233,15900000.0,NaN,5.100000e+07,-4100000.00,-4.060000e+07,8.792490e+08,6.197090e+08,2.568630e+08,6.136800e+07,2.584220e+08,4367000.0,17398000.0,NaN,NaN

In [51]:
# print("🔍 Companies not found in Excel mapping:")
# for name in not_found_unique:
#     print("-", name)

### Mapping JSON Aliases to Official Company Names

This block parses the `JsonNames` column from the Excel mapping file to extract known name aliases for each company. It builds a clear mapping from each alias to its official company name, helping resolve inconsistencies between report data and the reference ticker list. The result is printed in a readable format for verification.

In [52]:
# Create and print mapping: alias from 'JsonNames' → official company name
print("\n📌 JSON Alias Name → Official Company Name Mapping (from JsonNames column):\n")

alias_to_real = []

for _, row in mapping_df.iterrows():
    real_name = str(row['CompanyName']).strip()
    json_names = row['JsonNames']

    if isinstance(json_names, str) and json_names:
        try:
            parsed = ast.literal_eval(json_names)
            if isinstance(parsed, list):
                for alias in parsed:
                    alias = alias.strip()
                    if alias:
                        alias_to_real.append(f"'{alias}' --> '{real_name}'")
            else:
                alias = json_names.strip()
                if alias:
                    alias_to_real.append(f"'{alias}' --> '{real_name}'")
        except:
            alias = json_names.strip()
            if alias:
                alias_to_real.append(f"'{alias}' --> '{real_name}'")

# Sort alphabetically for readability
alias_to_real = sorted(set(alias_to_real))

for line in alias_to_real:
    print(line)

📌 JSON Alias Name → Official Company Name Mapping (from JsonNames column):

'"בזק" החברה הישראלית לתקשורת בע"מ' --> 'BEZEQ'
'(Y.Z) Queenco' --> 'QUEENCO'
'A. Luzon Real Estate and Finance' --> 'LUZON GROUP'
'A.I. Systems Conversation' --> 'AI SYSTEMS'
'A.S. Australia Israel Holdings' --> 'AUSTRALIA ISR'
'ALBAAD Massuot Yitzhak' --> 'ALBAAD'
'Abra Technologies Information' --> 'ABRA'
'Abra Technologies' --> 'ABRA'
'Accel Solutions Group' --> 'ACCEL'
'Adgar Investments & Development LTD.' --> 'ADGAR INVESTMENTS'
'Adgar Investments and Development' --> 'ADGAR INVESTMENTS'
'Afi Capital Nadlan' --> 'AFI PROPERTIES'
'Africa Israel Residences Ltd' --> 'AFRICA ISRAEL RESIDENCES'
'Airport City Ltd.' --> 'AIRPORT CITY'
'Airtouch Solar' --> 'AIRTOUCH'
'Alarum Technologies' --> 'ALARUM'
'Albad Masuot Yitzhak' --> 'ALBAAD'
'Allot Ltd.' --> 'ALLOT'
'Almeda Ventures Limited Partnership' --> 'ALMEDA PARTICIPATION UNIT'
'Almeda Ventures' --> 'ALMEDA PARTICIPATION UNIT'
'Almogim holdings' --> 'ALMOGIM'
'Alon Gas' --> 'DOR ALON'
'Alony Hetz Properties and Investments' --> 'ALONY HETZ'
'Alony-Hetz Properties & Investments' --> 'ALONY HETZ'
'Alrov Properties and Lodgings' --> 'ALROV PROPERTIES'
'Alrov Real Estate and Hotels' --> 'ALROV PROPERTIES'
'Aluma Fund Infrastructures (2020)' --> 'ALUMA INFRASTRUCTURES'
'Aluma Infrastructure Fund (2020)' --> 'ALUMA INFRASTRUCTURES'
'Amanet Management and Systems' --> 'AMANET'
'Amiad Water Systems' --> 'AMIAD'
'Amir Marketing and Investments in Agriculture' --> 'AMIR MARKETING'
'Amot Investments' --> 'AMOT'
'Apollo Power' --> 'APOLLO POWER'
'Arad Investment & Industrial Development LTD' --> 'ARAD INVESTMENT'
'Arad Investment & Industrial Development' --> 'ARAD INVESTMENT'
'Aran Research & Development' --> 'ARAN'
'Aran Research and Development (1982) Ltd.' --> 'ARAN'
'Ashot Ashkelon Industries' --> 'ASHOT'
'Ashtrom Group' --> 'ASHTROM GROUP'
'Aspen Group בע"מ' --> 'ASPEN GROUP'
'Aspen Group' --> 'ASPEN GROUP'
'AudioCodes' --> 'AUDIOCODES'
'Aura Investments Ltd.' --> 'AURA'
'Automax Motors' --> 'AUTOMAX'
'Averbuch Wood Products & Laminates' --> 'AVERBUCH'
'Avgol Industries 1953' --> 'AVGOL'
'Aviv Arlon Project d.o.o.' --> 'AVIV'
'Avrut Industries' --> 'AVROT'
'Axilion Smart Mobility' --> 'AXILION'
'Aylon Bituach Hanpakot Vegiusi Hon LTD' --> 'AYALON HOLD.'
'Aylon Insurance Issuances and Capital Raisings' --> 'AYALON HOLD.'
'Aylon Insurance Offerings and Capital Raisings' --> 'AYALON HOLD.'
'Azorim (CHF) Company for Investments in Development and Construction' --> 'AZORIM'
'Azorim Investment Company for Development and Construction' --> 'AZORIM'
'BATM Advanced Communications Limited' --> 'BATM'
'BLL Bull Trading and Investments' --> 'BULL TRADING'
'BLL Mischar VeHashkaot (Bull Commerce and Investments)' --> 'BULL TRADING'
'Bank Discount of Israel' --> 'DISCOUNT'
'Bank Hapoalim' --> 'POALIM'
'Bazan Group (Oil Refineries)' --> 'BAZAN'
'Bazan Group' --> 'BAZAN'
'Bee-io' --> 'BEEIO HONEY'
'Beit Bakfar' --> 'BAIT BAKFAR'
'Bet Shemesh Engines Holdings (1997) LTD.' --> 'BET SHEMESH'
'Bet Shemesh Engines Holdings' --> 'BET SHEMESH'
'Bezeq The Israeli Telecommunication Corp.' --> 'BEZEQ'
'Bicuri Sadeh' --> 'BIKUREY HASHDE'
'Big Mega Or Ltd.' --> 'MEGA OR'
'Big Mega Or' --> 'BIG'
'Big Shopping Centers' --> 'BIG'
'Big Tech 50 R&D' --> 'BIG-TECH 50 PARTICIPATION UNIT'
'Big-Tech 50 MOP - Limited Partnership' --> 'BIG-TECH 50 PARTICIPATION UNIT'
'Big-Tech 50 R&D - Limited Partnership' --> 'BIG-TECH 50 PARTICIPATION UNIT'
'Bikurei Sadeh (Holdings)' --> 'BIKUREY HASHDE'
'BioLineRx Ltd.' --> 'BIOLINE RX'
'Biolight Life Sciences' --> 'BIOLIGHT'
'Birman Trees and Hardware' --> 'BIRMAN'
'Blitz Technologies' --> 'BLITZ-MOTORS'
'Boni Hatichon Engineering Civil Engineering and Infrastructure' --> 'BONEI TICHON'
'Boni Hatichon Engineering and Infrastructure' --> 'BONEI TICHON'
'Bonus BioGroup' --> 'BONUS BIOGROUP'
'Brack Capital Properties N.V.' --> 'BRACK CAPITAL PROPERTIES'
'Bram Industries' --> 'BRAM INDUSTRIES'
'Brand Group (M.G.)' --> 'BRILL'
'Brand Industries' --> 'BRAND'
'Brill Shoe Industries LTD' --> 'BRILL'
'Buligo Capital' --> 'BULIGO'
'Bull Commerce and Investments' --> 'BULL TRADING'
'C.I. Systems (Israel) Ltd.' --> 'C I SYSTEMS'
'C.I. Systems (Israel)' --> 'C I SYSTEMS'
'CLAL BIOTECHNOLOGY INDUSTRIES' --> 'CLAL BIOTECH'
'Camtek LTD.' --> 'CAMTEK'
'Can-Fite BioPharma Ltd.' --> 'CAN FITE BIOFARMA'
'Carmit Candy Industries' --> 'CARMIT'
'Carse Motors' --> 'CARASSO MOTORS'
'Castro Model' --> 'CASTRO'
'Cellcom Israel' --> 'CELLCOM'
'Clal Biotechnology Industries' --> 'CLAL BIOTECH'
'Clal Insurance Enterprises Holdings' --> 'CLAL INSURANCE'
'Clalbit Finance' --> 'CLAL INSURANCE'
'Coffix Group Ltd.' --> 'COFIX GROUP'
'Cohen Development Gas and Oil' --> 'COHEN DEVELOPMENT'
'Compugen Ltd.' --> 'COMPUGEN'
'D.N.A Biomedical Solutions' --> 'DNA GROUP'
'DANEAL (ADIR YEHOSHUA) LTD' --> 'DANEL'
'DISCOUNT INVESTMENT CORPORATION' --> 'DISCOUNT INVESTMENTS'
'Dan Hotels Ltd.' --> 'DAN HOTELS'
'Danaal (Adir Yehoshua)' --> 'DANEL'
'Danya Cebus' --> 'DANYA CEBUS'
'Delek Drilling' --> 'DELEK GROUP'
'Delek Group' --> 'DELEK GROUP'
'Delek Motors Systems' --> 'DELEK AUTOMOTIV'
'Delek Motors Vehicle Systems' --> 'DELEK AUTOMOTIV'
'Delek Motors' --> 'DELEK AUTOMOTIV'
'Delta Galil Industries' --> 'DELTA GALIL'
'Delta Galil תעשיות בע"מ' --> 'DELTA GALIL'
'Delta Israel Brands' --> 'DELTA BRANDS'
'Discount Investment Corporation' --> 'DISCOUNT INVESTMENTS'
'Discount Issuing' --> 'DISCOUNT INVESTMENTS'
'Discount of Israel' --> 'DISCOUNT'
'Dor Alon Energy in Israel' --> 'DOR ALON'
'Doral Renewable Energy Resources' --> 'DORAL ENERGY'
'Dorsal (B.A.Z.)' --> 'DORSEL HOLDINGS'
'E. Luzon Real Estate and Finance' --> 'LUZON GROUP'
'E.N. Shoham Business' --> 'SHOHAM BUSINESS'
'ELECTRA MULTIFAMILY INVESTMENTS FUND II, L.P.' --> 'ELECTRA POWER'
'ELECTRA TRANSCENDENT SFR, LLC' --> 'ELECTRA'
'ELLOMAY CAPITAL LTD.' --> 'ELLOMAY'
'EMET E&M COMPUTING' --> 'EMET'
'ENERGIX RENEWABLES' --> 'ENERGIX'
'ENLIVEX THERAPEUTICS LTD.' --> 'ENLIVEX'
'Econergy Archmore S.a.r.l' --> 'ECONERGY'
'Econergy Energy' --> 'ECONERGY'
'Ecoppia Scientific' --> 'ECOPPIA'
'El Al Israel Airlines' --> 'EL AL'
'Elbit Systems' --> 'ELBIT SYSTEMS'
'Elco Ltd.' --> 'ELCO'
'Electra Consumer Products (1970)' --> 'ELECTRA CONSUMER PRODUCTS'
'Electra Multifamily Investments Fund II, L.P.' --> 'ELECTRA POWER'
'Electra Multifamily Investments Fund, L.P.' --> 'ELECTRA POWER'
'Electra Real Estate' --> 'ELECTRA REAL ESTATE'
'Electra' --> 'ELECTRA'
'Electreon Wireless' --> 'ELECTREON'
'Ellomay Capital' --> 'ELLOMAY'
'Elmor Electrical Installations and Services (1986)' --> 'ELMOR'
'Elspec Engineering' --> 'ELSPEC'
'Emilia' --> 'EMILIA DEVELOPMENT'
'Energean plc' --> 'ENERGEAN'
'Energix Renewable Energies Ltd.' --> 'ENERGIX'
'Energix Renewables' --> 'ENERGIX'
'Enlight Renewable Energy' --> 'ENLIGHT ENERGY'
'Enlivex Therapeutics' --> 'ENLIVEX'
'Equital' --> 'EQUITAL'
'Export Investment Corporation LTD.' --> 'EXPORT INVESTMENT'
'FIBI Holdings Ltd.' --> 'FIBI HOLDINGS'
'FMS Enterprises Migun' --> 'FMS'
'FORESIGHT AUTONOMOUS HOLDINGS LTD.' --> 'FORESIGHT'
'FOX - ויזל בעיימ' --> 'FOX'
'Fattal Holdings (1998)' --> 'FATAL HOLDINGS'
'Fattal-Issta Holdings' --> 'FATAL HOLDINGS'
'Foresight Autonomous Holdings Ltd.' --> 'FORESIGHT'
'Formula Systems (1985) LTD.' --> 'FORMOLA'
'Formula Systems (1985)' --> 'FORMOLA'
'Fox-Wiesel' --> 'FOX'
'G. WILLI-FOOD INTERNATIONAL LTD.' --> 'WILLY FOOD INTERNATIONAL'
'G. Willi-Food International' --> 'WILLY FOOD INTERNATIONAL'
'GIBUI (Gibui Achzakot B.M.)' --> 'GIBUI HOLDING'
'GOTO Global Mobility' --> 'GO TO'
'Gamla-Harel Nadlan Lemegurim' --> 'GAMLA HAREL'
'Gan Shmuel Group' --> 'GAN SHMUEL'
'Gaon Group' --> 'GAON GROUP'
'Gav-Yam Land Corp' --> 'GAV YAM'
'Gav-Yam Lands Corp.' --> 'GAV YAM'
'Gav-Yam Maman Properties in Lod' --> 'GAV YAM'
'Gefen Investments Biomed' --> 'GEFFEN RESIDENCE & RENEWAL'
'Generation Capital' --> 'GENERATION CAPITAL'
'Gev Yam Maman Lod' --> 'GAV YAM'
'Gilat Satellite Networks' --> 'GILAT'
'Gilat Telecom Global' --> 'GILAT TELECOM'
'Ginegar Plastic Product Ltd' --> 'GINEGAR'
'Ginegar Plastic Product' --> 'GINEGAR'
'Giv'ot Olam Oil Exploration Limited Partnership (1993)' --> 'GIVOT PARTICIPATION UNIT'
'Global Knafaim Leasing' --> 'GLOBAL KNAFAIM'
'Golan Plastic Products' --> 'GOLAN INDUSTRIES'
'Gold Bond Group' --> 'GOLD'
'Golden House Ltd' --> 'GOLDEN HOUSE'
'Golf Group' --> 'GOLF'
'HIPER GLOBAL בעיימ' --> 'HIPER GLOBAL'
'HIVE 2040 R&D LIMITED PARTNERSHIP' --> 'HIVE 2040 PARTICIPATION UNIT'
'HaBynleomy Hrashon Hnpoqt Bae’m' --> 'FIBI BANK'
'Hachsharat Hayeshuv' --> 'ISRAEL LAND DEVELOPMENT COMPANY'
'Hachsharat Hayishuv Israe' --> 'ISRAEL LAND DEVELOPMENT COMPANY'
'Hadasit Bio-Holdings' --> 'HADASIT BIO'
'Hagag Europe Development C.S.' --> 'HAGAG EUROPE'
'Hagag Europe Development' --> 'HAGAG EUROPE'
'Hagag Group Real Estate Entrepreneurship' --> 'HAGAG'
'Hagag Group Real Estate Initiatives' --> 'HAGAG'
'Ham-Let (Israel-Canada)' --> 'ISRAEL CANADA'
'Hamama Meir Sechar (1996)' --> 'HAMAMA'
'Hamat Group' --> 'HAMAT'
'Hapoalim Issuances' --> 'POALIM'
'Harel Insurance Finance and Issues' --> 'HAREL'
'Harel Insurance Investment and Financing' --> 'HAREL'
'Hilan Ltd' --> 'HILAN'
'Hiron-Commerce Investments and Industrial Buildings' --> 'HIRON'
'Hiron-Investment Trade and Industrial Buildings' --> 'HIRON'
'Hive 2040 R&D Limited Partnership' --> 'HIVE 2040 PARTICIPATION UNIT'
'Holmes Place International' --> 'HOLMES PLACE'
'Home Biogas' --> 'HOMEBIOGAS'
'Human Xtensions' --> 'HUMAN XT'
'ICL GROUP LTD.' --> 'ICL'
'ICL Group Ltd.' --> 'ICL'
'IDI Insurance Company Ltd.' --> 'IDI INSURANCE'
'ISRAIRGROUP' --> 'ISRAIR GROUP'
'Identi Healthcare' --> 'IDENTI'
'ImageSat International (ISI)' --> 'IMAGESAT I.S.I'
'Imco Industries LTD.' --> 'IMCO'
'Imed Infinity Medical' --> 'IMED PARTICIPATION UNIT'
'Infimer' --> 'INFEMIL'
'Inrom Industries' --> 'INROM CONSTRUCTION INDUSTRIES'
'Inter Industries Plus Ltd.' --> 'INTER INDUSTRIES'
'Intercure' --> 'INTERCURE'
'Internet Gold - Golden Lines' --> 'INTERNET GOLD'
'Israel Corp' --> 'THE ISRAEL CORPORATION'
'Israel Petrochemical Enterprises' --> 'PETROCHEMICAL'
'Israel Ports Development & Assets Company Ltd.' --> 'ISRAEL SHIPYARD'
'Israel Shipyards Industries' --> 'ISRAEL SHIPYARD'
'Israeli Opportunity - Energy Sources, Limited Partnership' --> 'ISRAEL OPPORTUNITY PARTICIPATION UNIT'
'Isramco Negev 2' --> 'ISRAMCO PARTICIPATION UNIT'
'Issta Lines' --> 'ISSTA'
'JUNGO Connectivity' --> 'JUNGO'
'Jerusalem Finance and Issues' --> 'JERUSALEM'
'Kafrit Industries (1993)' --> 'KAFRIT'
'Kafrit Industries' --> 'KAFRIT'
'Kafrit תעשיות (1993) בע"מ' --> 'KAFRIT'
'Kamada Ltd.' --> 'KAMADA'
'Kardan N.V.' --> 'KARDEN ISRAEL'
'Kardan Real Estate Development' --> 'KARDEN REAL ESTATE'
'Karsso Motors' --> 'CARASSO MOTORS'
'Kenon Holdings Ltd.' --> 'KENON'
'Kerur Holdings' --> 'KERUR'
'Keystone REIT' --> 'KEYSTONE INFRA'
'Klil Industries' --> 'KLIL'
'LIVEPERSON, INC.' --> 'LIVEPERSON'
'Lachish Industries LTD' --> 'LACHISH'
'Lahav LR Real Estate' --> 'LAHAV'
'Lapidoth Capital' --> 'LAPIDOTH-HELETZ - LIMITD PARTNERSHIP'
'Lesico' --> 'LESICO'
'Levinstin Properties Ltd.' --> 'LEVINSTEIN PROPERTIES'
'Lewinski-Ofer' --> 'LEVINSKI OFER'
'Libra Insurance Company' --> 'LIBRA'
'Lineage Cell Therapeutics Inc.' --> 'LINEAGE THERAPY'
'Lineage Cell Therapeutics, Inc.' --> 'LINEAGE THERAPY'
'Living RIT Azorim - H.P. Living' --> 'AZORIM'
'Loden Corporation for Engineering' --> 'LUDAN'
'M.L.R.N Projects and Trade' --> 'MLRN'
'M.L.R.N. Projects and Trading' --> 'MLRN'
'MALAM TEAM' --> 'MALAM TEAM'
'MASSIVIt 3D' --> 'MASSIVIT'
'MAX STOCK' --> 'MAX STOCK'
'MAYTRONICS' --> 'MAYTRONICS'
'MEGA OR' --> 'MEGA OR'
'MEHADRIN' --> 'MEHADRIN'
'MELISRON' --> 'MELISRON'
'MICRONET' --> 'MICRONET'
'MIRLAND DEVELOPMENT CORPORATION' --> 'MIRLAND DEVELOPMENT CORPORATION'
'MIVTACH SHAMIR' --> 'MIVTACH SHAMIR'
'MIZRAHI TEFAHOT' --> 'MIZRAHI TEFAHOT'
'MLRN Projects & Trading' --> 'MLRN'
'Magic Software Enterprises' --> 'MAGIC'
'Magurit Israel' --> 'MGURIT'
'Magurite Israel' --> 'MGURIT'
'Manif - Financial Services' --> 'MENIF'
'Manivim REIT New Fund' --> 'MENIVIM REIT'
'Manivim REIT The New' --> 'MENIVIM REIT'
'Manivim REIT the New REIT' --> 'MENIVIM REIT'
'Massivit 3D Technologies Printing' --> 'MASSIVIT'
'Matrix I.T.' --> 'MATRIX'
'Matrix IT' --> 'MATRIX'
'Matrix אי.טי. בע"מ' --> 'MATRIX'
'Medipower Overseas (Public) Co. Limited' --> 'MEDIPOWER'
'Medipower Overseas Public Co. Limited' --> 'MEDIPOWER'
'Menara Ventures' --> 'MERARA PARTICIPATION UNIT'
'Mendelson Infrastructures & Industries' --> 'MENDELSON INFRASTRUCTURE'
'Mendelson Infrastructures and Industries' --> 'MENDELSON INFRASTRUCTURE'
'Menora Mivtachim Issuance Corporation' --> 'MENORA MIVTAHIM HOLDINGS'
'Meshulam Levinstein Engineering and Contracting' --> 'LEVINSTEIN ENGINEERING'
'Michman B.S.D.' --> 'MICHMAN'
'Mifalei P.M.S Migun' --> 'FMS'
'Migdal Insurance Capital Raising' --> 'MIGDAL INSURANCE'
'Migdalei Haim Hatichon' --> 'MEDITERRANEAN TOWERS LTD'
'Miklol Mimon' --> 'MICHLOL FINANCES'
'Millennium Foodtech' --> 'MILLENNIUM FOOD PARTICIPATION UNIT'
'Mimon Yashir (Direct Finance)' --> 'DIRECT FINANCE'
'Mimon Yashir' --> 'DIRECT FINANCE'
'Mishorim Real Estate Investments LTD' --> 'MISHORIM'
'Mishuv Yashir Group' --> 'COMPUTER DIRECT'
'Mivna Real Estate (K.D)' --> 'MIVNE'
'Mivneh Real Estate' --> 'MIVNE'
'Mizrahi Tefahot Company for Issues' --> 'MIZRAHI TEFAHOT'
'Mizrahi Tefahot Issuances Company' --> 'MIZRAHI TEFAHOT'
'Modiin Energy' --> 'MODIIN PPARTICIPATION UNITU'
'Mordechai Aviv Industries Construction (1973)' --> 'AVIV'
'Mordechai Aviv Industries Construction' --> 'AVIV'
'N.R. Spuntech Industries' --> 'SPUNTECH'
'NAVITAS PETROLEUM (שותפות מוגבלת)' --> 'NAVITAS PTRO PARTICIPATION UNIT'
'NICE LTD.' --> 'NICE'
'NUR Ink Innovations' --> 'NUR'
'Naphtha Israel Petroleum Corp.' --> 'NAPHTHA'
'Navitas Petroleum' --> 'NAVITAS PTRO PARTICIPATION UNIT'
'Nawi Brothers Group' --> 'NAWI'
'Neto M.ע. אחזקות בע"מ' --> 'NETO HOLDINGS'
'NextFerm Technologies' --> 'NEXTFERM'
'NextVision Stabilized Systems LTD' --> 'NEXT VISION'
'Nextage Therapeutics' --> 'NEXTAGE'
'Nextferm Technologies בע"מ' --> 'NEXTFERM'
'Nextferm Technologies' --> 'NEXTFERM'
'Nextgen Biomed' --> 'NEXTGEN'
'Nissan Medical Industries' --> 'NISSAN'
'Nofar' --> 'NOFAR ENERGY'
'Nova Measuring Instruments' --> 'NOVA'
'NoveLog (Pharm-Up 1966)' --> 'NOVOLOG'
'Novolog (Pharm-Up 1966)' --> 'NOVOLOG'
'Novolog The Health Care Group' --> 'NOVOLOG'
'OPC Rotem' --> 'OPC ENERGY'
'OPCENERGY' --> 'OPC ENERGY'
'ORAMED PHARMACEUTICALS INC.' --> 'ORAMED PHARM'
'Oramed Pharmaceuticals INC.' --> 'ORAMED PHARM'
'Oramed Pharmaceuticals Inc.' --> 'ORAMED PHARM'
'Orbit Technologies' --> 'ORBIT'
'Orian S.M.' --> 'ORIAN'
'Ormat Technologies, Inc.' --> 'ORMAT TECHNOLOGY'
'Oron Holdings and Investments' --> 'ORON GROUP'
'Overseas Commerce' --> 'OVERSEAS'
'PAYTON INDUSTRIES LTD.' --> 'PAYTON'
'PETROTX' --> 'PETROTX PARTICIPATION UNIT'
'PLASSON' --> 'PLASSON INDUS'
'PLURISTEM THERAPEUTICS INC.' --> 'PLURI'
'Palram Industries (1990)' --> 'PALRAM'
'Partner Communications Company' --> 'PARTNER'
'Payment Technologies' --> 'PAYMENT FINANCES'
'Payton Industries LTD.' --> 'PAYTON'
'Paz Oil Company' --> 'PAZ ENERGY'
'PetroTx' --> 'PETROTX PARTICIPATION UNIT'
'Petrotex Limited Partnership' --> 'PETROTX PARTICIPATION UNIT'
'PharmaCann Global' --> 'PHARMOCANN'
'Phoenix Capital Gains (2009)' --> 'PHOENIX'
'Phoenix Capital Raising (2009)' --> 'PHOENIX'
'Plasson Industries' --> 'PLASSON INDUS'
'Plasto-Cargal Group' --> 'PLASTO CARGAL'
'Plasto-Kargal Group' --> 'PLASTO CARGAL'
'Plastopil Hazorea' --> 'PLASTOFIL'
'Pluristem Therapeutics Inc.' --> 'PLURI'
'Polygon Nadlan' --> 'POLYGON'
'Polyram Industries Plastic' --> 'POLYRAM'
'Polyram Plastic Industries' --> 'POLYRAM'
'Prashkovsky Investments and Building' --> 'PRASHKOVSKY'
'Prashkovsky Investments and Construction' --> 'PRASHKOVSKY'
'RAMON Investments & Holdings (1999) LTD' --> 'RAM ON'
'RANI ZIM SHOPPING CENTERS' --> 'RANI ZIM'
'RATIO ENERGIES' --> 'RATIO PARTICIPATION UNIT'
'REKAH PHARMACEUTICAL INDUSTRY' --> 'REKAH'
'ROBO Group LTD.' --> 'ROBOGROUP'
'RSL Electronics' --> 'RSL'
'Ralko Agencies' --> 'RALCO'
'Rami Levy Chain Stores Hashikma 2006' --> 'RAMI LEVI'
'Rami Levy Chain Stores Hashikma Marketing 2006' --> 'RAMI LEVI'
'Rami Levy Hashikma Marketing 2006' --> 'RAMI LEVI'
'Ramon Investments & Holdings (1999) LTD' --> 'RAM ON'
'Ramon Investments & Holdings LTD' --> 'RAM ON'
'Rani Zim Centers' --> 'RANI ZIM'
'Rapac Communication and Infrastructure' --> 'RAPAC'
'Ratio Oil Explorations (1992) Limited Partnership' --> 'RATIO PARTICIPATION UNIT'
'Ratio Petroleum Energy' --> 'RATIO PETROL PARTICIPATION UNIT'
'Ratio Petroleum' --> 'RATIO PETROL PARTICIPATION UNIT'
'Rav-Bariach Industries (08)' --> 'RAV BARIACH'
'Raval ACS' --> 'RAVAL'
'Rekah Pharmaceutical Industry' --> 'REKAH'
'Rimoni Industries' --> 'RIMONI'
'Rit Azorim - H.P. Living' --> 'REIT AZORIM LIVING'
'Rotem Energy Minerals' --> 'ROTEM ENERGY PARTICIPATION UNIT'
'Rotem Shani Initiatives and Investments' --> 'ROTEM ENERGY PARTICIPATION UNIT'
'Rotem Shani' --> 'ROTEM ENERGY PARTICIPATION UNIT'
'Rotshtein Real Estate' --> 'ROTSHTEIN'
'SAPIENS INTERNATIONAL CORPORATION N.V.' --> 'SAPIENS'
'SPACECOM' --> 'SPACE COMMUNICATION'
'STG International' --> 'STG'
'Sapiens International Corporation' --> 'SAPIENS'
'Savor Eat' --> 'SAVOREAT'
'Scope Group Metals' --> 'SCOPE'
'Scope Metals' --> 'SCOPE'
'Sela Istha Nadlan Israeli' --> 'SELLA REAL ESTATE'
'Sella Capital Real Estate' --> 'SELLA REAL ESTATE'
'Sella Istah Nadlan Israeli' --> 'SELLA REAL ESTATE'
'Shagrir Automotive Services' --> 'SHAGRIR'
'Shagrir Group Services' --> 'SHAGRIR'
'Shagrir Group Vehicle Services' --> 'SHAGRIR'
'Shamaim Improov' --> 'SHAMAYM'
'Shapir Engineering and Industry' --> 'SHAPIR ENGINEERING'
'Shemen Oil and Gas Resources' --> 'SHEMEN REAL ESTATE'
'Shniv Industries' --> 'SHANIV'
'Solaer Renewable Energies' --> 'SOLAER'
'Spacecom' --> 'SPACE COMMUNICATION'
'Spring Ventures' --> 'SPRING'
'Strawberry Fields REIT' --> 'STRAWBERRY INC'
'Summit Real Estate Group' --> 'SUMMIT'
'SureTech שור-טק' --> 'SURE TECH PARTICIPATION UNIT'
'Synel Mll Payway' --> 'SYNEL'
'TEUZA - A FAIRCHILD TECHNOLOGY VENTURE LTD.' --> 'TEUZA'
'TEVA PHARMACEUTICAL INDUSTRIES LIMITED' --> 'TEVA'
'TURPAZ Fragrances & Flavors' --> 'TURPAZ'
'Taddea Technology Development and Automation' --> 'TEDEA'
'Taya Ventures' --> 'TAYA INVESTMENTS'
'Techno Plus ventures' --> 'TCHNOPLS VENTURES'
'Technologies of Fire and Gas Detection' --> 'FIRE AND GAS DETECTION'
'Terminal X Online' --> 'TERMINAL X'
'Teuza - a Fairchild Technology Venture' --> 'TEUZA'
'Teva Pharmaceutical Industries' --> 'TEVA'
'The First International of Israel' --> 'FIBI BANK'
'The Phoenix Holdings' --> 'PHOENIX'
'Third Eye Vision' --> 'THIRDEYE'
'Tigbur - Manpower Professional Temporary' --> 'TIGBUR'
'Tigbur - Manpower Professional' --> 'TIGBUR'
'Togder Pharma' --> 'TOGETHER'
'Together Pharma' --> 'TOGETHER'
'Top Ramdor Systems and Computers (1990)' --> 'TOP SYSTEMS'
'Tower Semiconductor' --> 'TOWER'
'Trucknet Enterprise' --> 'TRUCKNET'
'Turpaz Fragrances & Flavors Industries' --> 'TURPAZ'
'UMH PROPERTIES, INC.' --> 'UMH'
'UNIC-TECH FUND' --> 'UNIC-TECH PARTICIPATION UNIT'
'Unetcredit Financial Services' --> 'UNET CREDIT'
'Unicorn Technologies' --> 'UNICORN TECH PARTICIPATION UNIT'
'Unique-Tech Limited Partnership' --> 'UNIC-TECH PARTICIPATION UNIT'
'Unitronics (1989) (R.G.)' --> 'UNITRONICS'
'Univo Pharmaceuticals' --> 'UNIVO'
'Upsellon Brands Holding' --> 'UPSELLON BRANDS'
'VERIDIS ENVIRONMENT' --> 'VERIDIS'
'Veridis Environment' --> 'VERIDIS'
'Victory Retail Supermarkets' --> 'VICTORY'
'Victory Supermarket Chain' --> 'VICTORY'
'Villar International' --> 'VILLAR'
'Waterstone Properties,' --> 'WATER IO'
'WeSure' --> 'WESURE GLOBALT'
'Willi-Food Investments' --> 'WILLT FOOD'
'XTL BIOPHARMACEUTICALS LTD.' --> 'XTL BIO'
'XTL Biopharmaceuticals' --> 'XTL BIO'
'Y.H. Dimri Construction and Development' --> 'DIMRI'

In [53]:
df_final_cleaned

,Company Name,Report Date,Revenue,Net Income,Earnings Per Share (EPS),Gross Profit,Operating Income (EBIT),Operating Cash Flow,Investing Cash Flow,Financing Cash Flow,Total Assets,Total Liabilities,Short-Term Debt,Long-Term Debt,Shareholders’ Equity,Dividends Paid,Number of Outstanding Shares,Guidance/Forecast,Key Performance Indicators (KPIs)
0,LUZON GROUP,"March 31, 2021",NaN,-671000.00,-0.420,NaN,NaN,-2.738000e+06,922000.00,2.123000e+06,1.196170e+08,3.746600e+07,1.372500e+07,3.500000e+05,8.180100e+07,NaN,NaN,NaN,NaN
1,ADAMA Agricultural Solutions,"March 31, 2021",1.020000e+09,34000000.00,NaN,285000000.0,76000000.00,-1.170000e+08,-73000000.00,2.361120e+08,6.200215e+09,3.727711e+09,5.381044e+08,1.419233e+09,2.473000e+09,NaN,137990881.0,NaN,NaN
2,ARKO Corp.,"March 31, 2021",1.484356e+09,-14662000.00,-0.130,NaN,13239000.00,1.127600e+07,-16645000.00,-8.314300e+07,2.650554e+09,2.371232e+09,2.949500e+07,6.447640e+08,1.794690e+08,NaN,124428000.0,NaN,NaN
3,ACCEL,"March 31, 2021",2.117600e+07,297000.00,0.001,4179000.0,NaN,-4.652000e+06,-8180000.00,2.013500e+07,1.296330e+08,7.807100e+07,6.080000e+05,1.316000e+06,6.890500e+07,NaN,NaN,NaN,NaN
4,Ace Capital Retail (2016),"March 31, 2021",1.794160e+08,8532000.00,0.370,80074000.0,14356000.00,NaN,NaN,NaN,8.122480e+08,6.703890e+08,NaN,NaN,1.418590e+08,20300000.0,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
350,"Zhuhai ACCESS Semiconductor Co.,","March 31, 2021",2.974263e+08,36510319.75,NaN,NaN,38801318.25,4.614806e+07,-21847834.12,2.460594e+07,2.013603e+09,9.868398e+08,7.397944e+07,4.394626e+08,1.026763e+09,NaN,694810165.0,NaN,NaN
351,Zim Urban by Rani Zim,"March 31, 2021",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
352,Ziviel Investments,"March 31, 2021",1.906000e+07,-1595000.00,NaN,4438000.0,4438000.00,1.119700e+07,-106000.00,-6.061000e+06,3.761870e+08,2.564340e+08,1.258000e+07,1.838720e+08,1.197530e+08,NaN,NaN,NaN,NaN
353,ZUR,"March 31, 2021",NaN,NaN,NaN,NaN,NaN,5.410500e+08,76227000.00,8.118320e+08,1.529148e+10,8.154560e+09,NaN,NaN,1.802194e+09,8000000.0,64954008.0,NaN,NaN
354,Zvi Zarfati & Sons Investments and Building 1992,"March 31, 2021",5.800000e+07,5500000.00,0.233,15900000.0,NaN,5.100000e+07,-4100000.00,-4.060000e+07,8.792490e+08,6.197090e+08,2.568630e+08,6.136800e+07,2.584220e+08,4367000.0,17398000.0,NaN,NaN

### Alias Resolution and Final Deduplication

This final cleaning phase ensures that company names appearing as aliases (from the `JsonNames` column) are mapped to their official names using a pre-built alias dictionary. After resolving all aliases, the dataset is filtered to retain only companies listed in the Excel mapping. For each matched company, the most complete record (least missing values) is selected, resulting in a clean and deduplicated DataFrame ready for export.

In [54]:
# Step 0: Normalize alias_to_real into a usable map
# (Assuming alias_to_real was built earlier as a list of "'alias' --> 'real_name'" strings)
alias_dict = {}
for line in alias_to_real:
    try:
        alias, real = line.split("-->")
        alias = alias.strip().strip("'").upper()
        real = real.strip().strip("'").upper()
        alias_dict[alias] = real
    except:
        continue

# Step 1: Replace aliases in df_final_cleaned using alias_dict
df_with_resolved_aliases = df_final_cleaned.copy()
df_with_resolved_aliases['Company Name'] = df_with_resolved_aliases['Company Name'].str.upper().str.strip()
df_with_resolved_aliases['Company Name'] = df_with_resolved_aliases['Company Name'].apply(
    lambda name: alias_dict.get(name, name)
)

# Step 2: Get all real company names from Excel
real_company_names_from_excel = mapping_df['CompanyName'].dropna().str.upper().unique().tolist()

# Step 3: Filter to include only companies that match Excel names after alias resolution
filtered_df = df_with_resolved_aliases[
    df_with_resolved_aliases['Company Name'].isin(real_company_names_from_excel)
].copy()

# Step 4: For each company, keep the row with the fewest NaNs
best_rows = []
for company_name in filtered_df['Company Name'].unique():
    group = filtered_df[filtered_df['Company Name'] == company_name]
    best_row = group.loc[group.isna().sum(axis=1).idxmin()]
    best_rows.append(best_row)

# Step 5: Final deduplicated DataFrame
df_final_deduped = pd.DataFrame(best_rows).reset_index(drop=True)

# Show result
print("✅ Deduplicated DataFrame shape:", df_final_deduped.shape)
df_final_deduped

✅ Deduplicated DataFrame shape: (188, 19)

,Company Name,Report Date,Revenue,Net Income,Earnings Per Share (EPS),Gross Profit,Operating Income (EBIT),Operating Cash Flow,Investing Cash Flow,Financing Cash Flow,Total Assets,Total Liabilities,Short-Term Debt,Long-Term Debt,Shareholders’ Equity,Dividends Paid,Number of Outstanding Shares,Guidance/Forecast,Key Performance Indicators (KPIs)
0,LUZON GROUP,"March 31, 2021",NaN,-671000.0,-0.420,NaN,NaN,-2738000.0,922000.0,2123000.0,1.196170e+08,3.746600e+07,1.372500e+07,3.500000e+05,8.180100e+07,NaN,NaN,NaN,NaN
1,ACCEL,"March 31, 2021",21176000.0,297000.0,0.001,4179000.0,NaN,-4652000.0,-8180000.0,20135000.0,1.296330e+08,7.807100e+07,6.080000e+05,1.316000e+06,6.890500e+07,NaN,NaN,NaN,NaN
2,AFI PROPERTIES,2021-03-31,NaN,50300000.0,NaN,NaN,NaN,NaN,NaN,NaN,1.364527e+10,NaN,NaN,NaN,4.280821e+09,NaN,NaN,NaN,NaN
3,AIRPORT CITY,31.3.2021,NaN,191952000.0,1.500,610012000.0,337388000.0,NaN,NaN,NaN,1.526052e+10,7.580465e+09,1.329952e+09,4.041292e+09,7.477794e+09,NaN,NaN,The Company cannot estimate the full impact of...,NaN
4,ALBAAD,"March 31, 2021",371345000.0,32419000.0,3.050,97596000.0,43640000.0,NaN,NaN,NaN,1.482447e+09,9.654570e+08,NaN,NaN,5.169900e+08,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
183,YBOX,"March 31, 2021",130650000.0,25364000.0,0.130,21030000.0,39034000.0,6470000.0,-4141000.0,-1501000.0,6.367670e+08,4.171630e+08,1.461170e+08,1.929830e+08,2.196040e+08,NaN,NaN,NaN,NaN
184,YAACOBI GROUP,"March 31, 2021",106508000.0,252000.0,NaN,11287000.0,1468000.0,NaN,5712000.0,-32056000.0,5.059090e+08,2.463950e+08,5.894700e+07,2.914300e+07,1.959800e+08,NaN,NaN,The company estimates that in 2022 and after c...,NaN
185,ISRAS,"March 31, 2021",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.208940e+06,3.967830e+06,6.877010e+05,NaN,3.553409e+06,NaN,NaN,NaN,NaN
186,UNET CREDIT,"March 31, 2021",12742000.0,-11395000.0,-2.560,NaN,NaN,-31597000.0,-2372000.0,69991000.0,1.158610e+08,8.507400e+07,4.796000e+07,4.239600e+07,3.078700e+07,NaN,NaN,NaN,NaN
187,ZUR,"March 31, 2021",NaN,NaN,NaN,NaN,NaN,541050000.0,76227000.0,811832000.0,1.529148e+10,8.154560e+09,NaN,NaN,1.802194e+09,8000000.0,64954008.0,NaN,NaN

### Exporting to drive

In [55]:
df_final_deduped.to_csv("/content/drive/Shareddrives/capstone project-stock market robo-advisor/Reports Parameters/report_analysis_2021_q1.csv")